Repository umc-owncast/OwnCast_backend, pull requests merged in 2024-08, with the labels that each got.

#28 [FEATURE] Script 번역 기능 구현
  build.gradle
  src/main/java/com/umc/owncast/domain/cast/controller/CastController.java
  src/main/java/com/umc/owncast/domain/cast/service/CastService.java
  src/main/java/com/umc/owncast/domain/cast/service/ScriptService.java
  src/main/java/com/umc/owncast/domain/cast/service/TTSService.java
  src/main/java/com/umc/owncast/domain/cast/service/TranslateService.java
Labels: 💻 FEATURE

#31 [CI] ci/cd 환경 구축 변경
  .github/workflows/dev_deploy.yml
Labels: ⚙ CORE

#34 [FEAT] S3관련 파일 업로드 설정
  .github/workflows/dev_deploy.yml
  build.gradle
  src/main/java/com/umc/owncast/common/config/AwsS3Config.java
  src/main/java/com/umc/owncast/domain/cast/service/FileService.java
  src/main/java/com/umc/owncast/domain/cast/service/TTSService.java
Labels: 💻 FEATURE

#36 [FEATURE] Voice Enum 처리 & Sentence save 로직 구현
  src/main/java/com/umc/owncast/OwncastApplication.java
  src/main/java/com/umc/owncast/common/entity/BaseTimeEntity.java
  src/main/java/com/umc/owncast/domain/cast/controller/CastController.java
  src/main/java/com/umc/owncast/domain/cast/dto/TTSResultDTO.java
  src/main/java/com/umc/owncast/domain/cast/enums/VoiceCode.java
  src/main/java/com/umc/owncast/domain/cast/service/CastService.java
  src/main/java/com/umc/owncast/domain/cast/service/FileService.java
  src/main/java/com/umc/owncast/domain/cast/service/TTSService.java
  src/main/java/com/umc/owncast/domain/sentence/entity/Sentence.java
  src/main/java/com/umc/owncast/domain/sentence/service/SentenceService.java
  src/main/java/com/umc/owncast/domain/sentence/service/SentenceServiceImpl.java
Labels: 💻 FEATURE

#62 회원 관련 api 수정
  src/main/java/com/umc/owncast/common/config/SecurityConfig.java
  src/main/java/com/umc/owncast/common/config/WebConfig.java
  src/main/java/com/umc/owncast/common/jwt/LoginFilter.java
  src/main/java/com/umc/owncast/common/jwt/LoginService.java
  src/main/java/com/umc/owncast/domain/cast/entity/Cast.java
  src/main/java/com/umc/owncast/domain/category/repository/MainCategoryRepository.java
  src/main/java/com/umc/owncast/domain/category/repository/SubCategoryRepository.java
  src/main/java/com/umc/owncast/domain/enums/Language.java
  src/main/java/com/umc/owncast/domain/language/entity/Language.java
  src/main/java/com/umc/owncast/domain/language/repository/LanguageRepository.java
  src/main/java/com/umc/owncast/domain/member/annotation/AuthUser.java
  src/main/java/com/umc/owncast/domain/member/annotation/AuthUserArgumentResolver.java
  src/main/java/com/umc/owncast/domain/member/controller/MemberController.java
  src/main/java/com/umc/owncast/domain/member/dto/CustomUserDetails.java
  src/main/java/com/umc/owncast/domain/member/dto/LanguageDTO.java
  src/main/java/com/umc/owncast/domain/member/dto/MemberPreferRequestDTO.java
  src/main/java/com/umc/owncast/domain/member/dto/MemberRequest.java
  src/main/java/com/umc/owncast/domain/member/dto/MemberResponse.java
  src/main/java/com/umc/owncast/domain/member/dto/RefreshTokenDto.java
  src/main/java/com/umc/owncast/domain/member/entity/Member.java
  src/main/java/com/umc/owncast/domain/member/service/MemberMapper.java
  src/main/java/com/umc/owncast/domain/member/service/MemberService.java
Labels: 💻 FEATURE, 🛠 REFACTOR

#65 feat: 외부 API 실행시간 추적
  src/main/java/com/umc/owncast/domain/cast/service/TTSService.java
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/ChatGPTAnswerGenerator.java
  src/main/java/com/umc/owncast/domain/sentence/service/TranslateService.java
Labels: :bulb: ENHANCEMENT

#71 update: 스크립트 번역 개선
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/ChatGptAnswerGenerator.java
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/ChatGptPromptGenerator.java
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/keyword/KeywordServiceImpl.java
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/script/ChatGptScriptService.java
  src/main/java/com/umc/owncast/domain/sentence/service/ChatGptTranslationService.java
  src/main/java/com/umc/owncast/domain/sentence/service/PapagoTranslationService.java
  src/main/java/com/umc/owncast/domain/sentence/service/SentenceServiceImpl.java
  src/main/java/com/umc/owncast/domain/sentence/service/TranslationService.java
Labels: :bulb: ENHANCEMENT

#70 update: 캐스트 수정 API 업데이트
  src/main/java/com/umc/owncast/common/response/status/SuccessCode.java
  src/main/java/com/umc/owncast/common/util/StringUtil.java
  src/main/java/com/umc/owncast/domain/cast/controller/CastController.java
  src/main/java/com/umc/owncast/domain/cast/dto/CastSaveDTO.java
  src/main/java/com/umc/owncast/domain/cast/dto/CastUpdateRequestDTO.java
  src/main/java/com/umc/owncast/domain/cast/entity/Cast.java
  src/main/java/com/umc/owncast/domain/cast/service/CastService.java
  src/main/java/com/umc/owncast/domain/cast/service/CastServiceImpl.java
  src/main/java/com/umc/owncast/domain/cast/service/FileService.java
  src/main/java/com/umc/owncast/domain/castplaylist/repository/CastPlaylistRepository.java
Labels: :bulb: ENHANCEMENT

#90 Update dev_deploy.yml
  .github/workflows/dev_deploy.yml
Labels: :bulb: ENHANCEMENT

#92 fix: main category enum 작업
  src/main/java/com/umc/owncast/domain/cast/controller/CastController.java
  src/main/java/com/umc/owncast/domain/cast/dto/HomeDTO.java
  src/main/java/com/umc/owncast/domain/cast/repository/CastRepository.java
  src/main/java/com/umc/owncast/domain/cast/service/CastServiceImpl.java
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/keyword/KeywordService.java
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/keyword/KeywordServiceImpl.java
  src/main/java/com/umc/owncast/domain/castcategory/entity/CastMainCategory.java
  src/main/java/com/umc/owncast/domain/castcategory/entity/CastSubCategory.java
  src/main/java/com/umc/owncast/domain/castcategory/repository/CastMainCategoryRepository.java
  src/main/java/com/umc/owncast/domain/category/Initializer/MainCategoryInitializer.java
  src/main/java/com/umc/owncast/domain/category/Initializer/SubCategoryInitializer.java
  src/main/java/com/umc/owncast/domain/category/entity/MainCategory.java
  src/main/java/com/umc/owncast/domain/category/entity/SubCategory.java
  src/main/java/com/umc/owncast/domain/category/repository/MainCategoryRepository.java
  src/main/java/com/umc/owncast/domain/category/repository/SubCategoryRepository.java
  src/main/java/com/umc/owncast/domain/enums/MainCategory.java
  src/main/java/com/umc/owncast/domain/member/controller/MemberController.java
  src/main/java/com/umc/owncast/domain/member/dto/MemberRequest.java
  src/main/java/com/umc/owncast/domain/member/service/MemberService.java
  src/main/java/com/umc/owncast/domain/memberprefer/entity/MainPrefer.java
  src/main/java/com/umc/owncast/domain/memberprefer/repository/MainPreferRepository.java
  src/main/java/com/umc/owncast/domain/memberprefer/repository/MemberPreferRepository.java
Labels: 🛠 REFACTOR

#95 enhance: TTS 5000 바이트 이상의 경우 분할 요청
  src/main/java/com/umc/owncast/domain/cast/dto/TTSTempDTO.java
  src/main/java/com/umc/owncast/domain/cast/service/CastServiceImpl.java
  src/main/java/com/umc/owncast/domain/cast/service/ParsingService.java
  src/main/java/com/umc/owncast/domain/cast/service/TTSService.java
  src/main/java/com/umc/owncast/domain/sentence/service/ChatGptTranslationService.java
  src/main/java/com/umc/owncast/domain/sentence/service/SentenceService.java
  src/main/java/com/umc/owncast/domain/sentence/service/SentenceServiceImpl.java
Labels: :bulb: ENHANCEMENT, 🛠 REFACTOR

#105 feat: voice 예시 오디오 API 추가
  src/main/java/com/umc/owncast/common/initializer/SubCategoryInitializer.java
  src/main/java/com/umc/owncast/common/initializer/VoiceExampleGenerator.java
  src/main/java/com/umc/owncast/common/response/status/ErrorCode.java
  src/main/java/com/umc/owncast/domain/cast/service/CastServiceImpl.java
  src/main/java/com/umc/owncast/domain/cast/service/chatGPT/script/ChatGptScriptService.java
  src/main/java/com/umc/owncast/domain/sentence/service/ChatGptTranslationService.java
  src/main/java/com/umc/owncast/domain/sentence/service/PapagoTranslationService.java
  src/main/java/com/umc/owncast/domain/sentence/service/TranslationService.java
  src/main/java/com/umc/owncast/domain/voiceexample/controller/VoiceExampleController.java
  src/main/java/com/umc/owncast/domain/voiceexample/dto/VoiceExampleDTO.java
  src/main/java/com/umc/owncast/domain/voiceexample/entity/VoiceExample.java
  src/main/java/com/umc/owncast/domain/voiceexample/repository/VoiceExampleRepository.java
  src/main/java/com/umc/owncast/domain/voiceexample/service/VoiceExampleService.java
Labels: 💻 FEATURE

#111 fix: member info get 정보 추가
  src/main/java/com/umc/owncast/domain/member/dto/MemberInfoDTO.java
  src/main/java/com/umc/owncast/domain/member/service/MemberService.java
Labels: 🛠 REFACTOR
